// Generated by CoffeeScript 1.9.3
(function() {
  var button, dl, i, makeRequest, new_panel_button, new_panel_event, new_template_button, new_textbox_button, new_textbox_event, output_textbox, template, test_button, textbox_text;

  dl = window.displayLib;

  makeRequest = function(data, location, method) {
    if (location == null) {
      location = '/';
    }
    if (method == null) {
      method = 'POST';
    }
    data = JSON.stringify(data);
    return new Promise(function(resolve, reject) {
      var _request;
      _request = new XMLHttpRequest();
      _request.open(method, location, true);
      _request.onload = function() {
        if (_request.status === 200) {
          return resolve(_request.response);
        } else {
          return reject(_request.statusText);
        }
      };
      _request.onerror = function() {
        return reject(_request);
      };
      _request.setRequestHeader('Content-Type', 'application/json; charset=UTF-8');
      return _request.send(data);
    });
  };

  new_template_button = document.getElementById("new_template");

  new_panel_button = document.getElementById("new_panel");

  new_textbox_button = document.getElementById("new_textbox");

  textbox_text = document.getElementById("text");

  test_button = document.getElementById("test_button");

  output_textbox = document.getElementById("output_textbox");

  button = document.getElementById('button');

  template = null;

  new_template_button.addEventListener('click', function(e) {
    var tc, vis;
    e.target.disabled = true;
    template = new dl.Template('first template');
    new_panel_button.disabled = false;
    new_panel_button.addEventListener('click', new_panel_event);
    new_textbox_button.disabled = false;
    new_textbox_button.addEventListener('click', new_textbox_event);
    vis = template.render();
    tc = document.getElementById('template-container');
    tc.appendChild(vis);
    return e.target.removeEventListener();
  });

  i = 0;

  new_panel_event = function(e) {
    var p1;
    p1 = new dl.Panel("panel " + (i + 1), new dl.XYInfo(0, 0, 60, 32));
    p1.control = 1 + i;
    p1.layout = 1 - i;
    p1.position = 1 + i;
    template.panels.push(p1);
    template.render();
    if (i < 2) {
      return i++;
    } else {
      e.target.disabled = true;
      return e.removeEventListener();
    }
  };

  new_textbox_event = function(e) {
    var tb;
    tb = new dl.Textbox(new dl.XYInfo(0, 0, 20, 10), textbox_text.value);
    template.elements.push(tb);
    return template.render();
  };

  test_button.addEventListener('click', function(e) {
    var ob;
    ob = template.serialize();
    return output_textbox.innerHTML = JSON.stringify(ob, null, 2);
  });

  button.onclick = function(e) {
    var ob;
    ob = template.serialize();
    return makeRequest(ob).then(function(res) {
      console.log('responded with');
      return console.log(res);
    });
  };

}).call(this);
